# Configuration for menu app
[[builds]]
base = "menu/"  # Directory where the menu app's package.json is located
publish = "menu/build"  # Output directory of the build
command = "npm run build"  # Build command for menu app

# Configuration for dashboard app
[[builds]]
base = "dashboard/"  # Directory where the dashboard app's package.json is located
publish = "dashboard/build"  # Output directory of the build
command = "npm run build"  # Build command for dashboard app
