# netlify.toml

[build]
  # Set the base directory for building the app from the monorepo root
  base = "/"

[[builds]]
  # Specify the build commands and the publish directories for each part of the app

  # Menu build configuration
  base = "menu"
  publish = "menu/build"
  command = "npm install && npm run build"

[[builds]]
  # Dashboard build configuration
  base = "dashboard"
  publish = "dashboard/build"
  command = "npm install && npm run build"

[[redirects]]
  from = "/menu/*"
  to = "/menu/index.html"
  status = 200
  force = true

[[redirects]]
  from = "/dashboard/*"
  to = "/dashboard/index.html"
  status = 200
  force = true