# netlify.toml

[[builds]]
  base = "dashboard"  # This points to the dashboard directory
  cmd = "npm install && npm run build"  # Run the build for the dashboard app
  publish = "dashboard/build"  # Specify the build directory for the dashboard app
  directory = "dashboard"  # Set the working directory for the dashboard

[[builds]]
  base = "menu"  # This points to the menu directory
  cmd = "npm install && npm run build"  # Run the build for the menu app
  publish = "menu/build"  # Specify the build directory for the menu app
  directory = "menu"  # Set the working directory for the menu
