[build]
  base = "."
  command = "npm run build:dashboard && npm run build:menu"
  publish = "build"

[scripts]
  build:dashboard = "cd dashboard && npm run build"
  build:menu = "cd menu && npm run build"
